package Encapsulation;

public class Constructor {// how to form a constructor
	
	/*
	 * IF YOU ARE MAKING SINGLE OR MULTIPLE CONSTRUCTOR THAN DEFALT CONSTRUCTOR WILL
	 * NOT BE GENERATED BY JAVA COMPILER i.e JVM
	 */
	
	private String colour;
	private double borderWidth;

	public Constructor() {

	}

	public Constructor(String colour, double borderWidth) {
		// will also work as a setter
		this.borderWidth = borderWidth;
		this.colour = colour;
	}

	public String getColour() {
		return colour;
	}

	public double getBorderWidth() {
		return borderWidth;
	}

}
